import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Queue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"text-blue-500 bg-azul"}>
        <header>
        <nav className="flex justify-between items-center pt-6 pb-2">
          <Link href='/'>
          
              <h1 className="text-3xl text-white font-semibold">Queueing Calculator</h1>
          </Link>
              <div className="flex items-center space-x-6">
                  <Link href="/" className="text-white font-semibold hover:underline">Home</Link>
                  <Link href="#" className="text-white font-semibold hover:underline">Contact</Link>
                  <Link href="#" className="text-white font-semibold hover:underline">About</Link>
                  <Link href="#" className="text-white"><i className="fas fa-user-cog"></i></Link>
              </div>
          </nav>
        </header>
        {children}
        <div className="absolute bottom-0 h-[80px] w-full space-y-6 text-center text-black">
                <div className="mx-[118px] bg-white pt-[2px]" />
                <div>© 2024  All rights reserved</div>
              </div>

      </body>
    </html>
  );
}
